name: "publish"

on:
  push:
    branches:
      - master
    paths:
      - "package/package.json"
      - ".github/workflows/publish.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Enable Corepack (for pnpm)
        run: corepack enable

      - name: Install Dependencies
        run: pnpm i
        working-directory: package

      - name: Lint Project
        run: pnpm run lint
        working-directory: package

      # - name: Run Tests
      #   run: pnpm test
      #   working-directory: package

      - name: Publish Package
        run: pnpm publish
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_SECRET }}
